[package]
name = "bodymovin"
version = "0.1.0"
edition = "2021"

[lib]
name = "bodymovin"
path = "src/lib.rs"

[dependencies]
serde_json = "1.0"
image = "0.24"
imageproc = "0.23.0"
rand = "0.8"
num-rational = "0.4.2"
rayon = "1.10.0"

[dev-dependencies]
tempfile = "3"  # Or the latest version