[package]
name = "bodymovin-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
image = "0.24"
imageproc = "0.23.0"
rand = "0.8"
num-rational = "0.4.2"
rayon = "1.10.0"
float-cmp = "0.9.0"